"use client";

import Link from "next/link";
import { useState } from "react";
import { Notice, post, useApi } from "../_components/shared";

type Term = { id: string; name: string; start_date: string; end_date: string; eligible_statuses: string; status: string; student_count: number; meeting_count: number; group_count: number };
type EditableTerm = Pick<Term, "id" | "name" | "start_date" | "end_date" | "eligible_statuses">;
type FormState = { name: string; startDate: string; endDate: string; eligibleStatuses: string[] };
const emptyForm: FormState = { name: "", startDate: "", endDate: "", eligibleStatuses: ["present"] };

export default function TermHomeClient({ canManage, initialEdit }: { canManage: boolean; initialEdit: EditableTerm | null }) {
  const state = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] });
  const [editingId, setEditingId] = useState(initialEdit?.id ?? ""); const [showForm, setShowForm] = useState(Boolean(initialEdit)); const [form, setForm] = useState<FormState>(initialEdit ? { name: initialEdit.name, startDate: initialEdit.start_date, endDate: initialEdit.end_date, eligibleStatuses: initialEdit.eligible_statuses.split(",").filter(Boolean) } : emptyForm); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const beginEdit = (term: Term) => { setEditingId(term.id); setForm({ name: term.name, startDate: term.start_date, endDate: term.end_date, eligibleStatuses: term.eligible_statuses.split(",").filter(Boolean) }); setShowForm(true); setMessage(""); };
  const beginCreate = () => { setEditingId(""); setForm(emptyForm); setShowForm(true); setMessage(""); };
  const save = async () => { setBusy(true); setMessage(""); try { await post("/api/terms", { id: editingId || undefined, name: form.name, startDate: form.startDate, endDate: form.endDate, eligibleStatuses: form.eligibleStatuses }); setMessage(editingId ? "학기 정보를 수정했습니다." : "새 학기를 만들었습니다."); setShowForm(false); setEditingId(""); setForm(emptyForm); await state.reload(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const remove = async (term: Term) => { const approved = window.confirm(`‘${term.name}’을 삭제할까요?\n\n이 학기의 학생 명단, 조 편성, 출결, 등단 기록도 함께 삭제됩니다. 업로드 원본 파일은 보존됩니다.`); if (!approved) return; setBusy(true); setMessage(""); try { await post("/api/terms", { action: "delete_term", id: term.id }); if (editingId === term.id) { setEditingId(""); setShowForm(false); setForm(emptyForm); } setMessage(`‘${term.name}’을 삭제했습니다.`); await state.reload(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const toggleEligible = (status: string) => setForm((current) => ({ ...current, eligibleStatuses: current.eligibleStatuses.includes(status) ? current.eligibleStatuses.filter((item) => item !== status) : [...current.eligibleStatuses, status] }));

  return <main className="term-home"><section className="term-landing"><div className="term-landing-copy"><p className="manage-eyebrow">WORSHIP TEAM OPERATIONS</p><h1>운영할 학기를<br />선택하세요.</h1><p>학기를 연 뒤에 해당 학기의 인원 DB, 조 편성, 출결과 등단을 관리할 수 있습니다.</p></div>{canManage && <button className="manage-primary term-add" type="button" onClick={beginCreate}>새 학기 추가 <span>＋</span></button>}</section>
    <section className="term-library" aria-labelledby="term-list-title"><div className="manage-section-head"><div><p>학기 선택</p><h2 id="term-list-title">내 학기</h2></div><span>{state.data.terms.length}개 학기</span></div>{message && <Notice error={message.includes("확인") || message.includes("이미") || message.includes("못")}>{message}</Notice>}{state.error && <Notice error>{state.error}</Notice>}{!state.loading && state.data.terms.length === 0 && <div className="term-empty"><span>01</span><h2>아직 학기가 없습니다.</h2><p>첫 학기를 추가하면 운영 준비를 시작할 수 있어요.</p>{canManage && <button className="manage-button primary" onClick={beginCreate}>첫 학기 추가</button>}</div>}<div className="term-card-grid">{state.data.terms.map((term) => <article className="term-card" key={term.id}><Link className="term-card-main" href={`/manage/terms/${term.id}`}><div><span className={`term-status ${term.status}`}>{term.status === "active" ? "진행 중" : "종료"}</span><span className="term-open">열기 →</span></div><h2>{term.name}</h2><p>{term.start_date} — {term.end_date}</p><dl><div><dt>학생</dt><dd>{term.student_count}명</dd></div><div><dt>모임</dt><dd>{term.meeting_count}회</dd></div><div><dt>조</dt><dd>{term.group_count}개</dd></div></dl></Link>{canManage && <div className="term-card-actions"><button type="button" onClick={() => beginEdit(term)}>수정</button><button className="danger" type="button" disabled={busy} onClick={() => void remove(term)}>삭제</button></div>}</article>)}</div></section>
    {showForm && <div className="term-form-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowForm(false); }}><section className="term-form" role="dialog" aria-modal="true" aria-labelledby="term-form-title"><div className="term-form-head"><div><p>{editingId ? "학기 수정" : "새 학기"}</p><h2 id="term-form-title">{editingId ? "학기 정보를 고쳐주세요." : "운영 기간을 정해주세요."}</h2></div><button type="button" aria-label="닫기" onClick={() => setShowForm(false)}>×</button></div><label className="manage-field">학기 이름<input className="manage-input" value={form.name} placeholder="2026년 2학기" onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><div className="manage-grid"><label className="manage-field">시작일<input className="manage-input" type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></label><label className="manage-field">종료일<input className="manage-input" type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></label></div><fieldset className="manage-field term-eligible"><legend>등단 인정 출결</legend>{[["present", "출석"], ["late", "지각"], ["left_early", "조퇴"]].map(([value, label]) => <label key={value}><input type="checkbox" checked={form.eligibleStatuses.includes(value)} onChange={() => toggleEligible(value)} /> {label}</label>)}</fieldset><p className="term-form-help">기간을 수정하면 범위 안의 토요일 일정이 자동으로 맞춰집니다.</p><div className="term-form-actions"><button className="manage-button" type="button" onClick={() => setShowForm(false)}>취소</button><button className="manage-button primary" type="button" disabled={busy || !form.name.trim() || !form.startDate || !form.endDate} onClick={() => void save()}>{busy ? "저장 중…" : editingId ? "수정 저장" : "학기 추가"}</button></div></section></div>}
  </main>;
}
