"use client";
import { useMemo, useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";
type Term = { id: string; name: string; start_date: string; end_date: string; eligible_statuses: string; status: string };
type Meeting = { id: string; term_id: string; meeting_date: string; kind: "regular" | "extra" | "break"; title: string | null };

export default function TermsClient() {
  const state = useApi<{ terms: Term[]; meetings: Meeting[] }>("/api/terms", { terms: [], meetings: [] }); const [selected, setSelected] = useState(""); const [message, setMessage] = useState("");
  const activeId = selected || state.data.terms.find((term) => term.status === "active")?.id || state.data.terms[0]?.id || ""; const meetings = useMemo(() => state.data.meetings.filter((item) => item.term_id === activeId), [state.data.meetings, activeId]);
  const saveTerm = async (form: FormData) => { try { await post("/api/terms", { name: form.get("name"), startDate: form.get("start"), endDate: form.get("end"), eligibleStatuses: form.getAll("eligible") }); setMessage("학기와 토요일 일정을 생성했습니다."); await state.reload(); } catch (error) { setMessage((error as Error).message); } };
  const toggle = async (meeting: Meeting) => { await post("/api/terms", { action: "set_meeting", termId: meeting.term_id, date: meeting.meeting_date, kind: meeting.kind === "break" ? "regular" : "break", title: meeting.title }); await state.reload(); };
  const addExtra = async (form: FormData) => { await post("/api/terms", { action: "set_meeting", termId: activeId, date: form.get("date"), kind: "extra", title: form.get("title") }); await state.reload(); };
  return <main className="manage-content"><PageTitle eyebrow="01 · TERM" title="학기와 모임 일정" detail="학기를 먼저 만들고 기간에서 토요일 모임 일정을 생성합니다." />
    <div className="manage-grid"><form className="manage-panel manage-stack" action={(form) => void saveTerm(form)}><h2>새 학기</h2><label className="manage-field">학기 이름<input className="manage-input" name="name" placeholder="2026년 2학기" required /></label><div className="manage-grid"><label className="manage-field">시작일<input className="manage-input" name="start" type="date" required /></label><label className="manage-field">종료일<input className="manage-input" name="end" type="date" required /></label></div><fieldset className="manage-field"><legend>등단 인정 출결</legend><label><input type="checkbox" name="eligible" value="present" defaultChecked /> 출석</label><label><input type="checkbox" name="eligible" value="late" /> 지각</label><label><input type="checkbox" name="eligible" value="left_early" /> 조퇴</label></fieldset><button className="manage-button primary">학기 생성</button>{message && <Notice>{message}</Notice>}</form>
    <section className="manage-panel manage-stack"><h2>학기 선택</h2><select className="manage-select" value={activeId} onChange={(event) => setSelected(event.target.value)}><option value="">학기를 선택하세요</option>{state.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name} · {term.status}</option>)}</select><form className="manage-toolbar" action={(form) => void addExtra(form)}><input className="manage-input" name="date" type="date" required /><input className="manage-input" name="title" placeholder="임시 모임 이름" /><button className="manage-button">임시 모임 추가</button></form></section></div>
    <section className="manage-panel" style={{ marginTop: 14 }}><h2>모임 일정</h2><div className="manage-list">{meetings.map((meeting) => <div className="manage-person" key={meeting.id}><div><b>{meeting.meeting_date}</b><br /><small>{meeting.kind === "break" ? "휴강" : meeting.kind === "extra" ? "임시 모임" : "정규 토요모임"}{meeting.title ? ` · ${meeting.title}` : ""}</small></div><button className={`manage-button${meeting.kind === "break" ? "" : " danger"}`} onClick={() => void toggle(meeting)}>{meeting.kind === "break" ? "모임으로 복원" : "휴강 지정"}</button></div>)}</div>{!meetings.length && <Notice>학기를 만들면 기간 안의 토요일이 자동 생성됩니다.</Notice>}</section>
  </main>;
}
