"use client";
import { type DragEvent, useMemo, useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";

type Term = { id: string; name: string; status: string };
type Meeting = { id: string; meeting_date: string };
type Person = { id: string; name: string; gender?: string | null; service_part?: number; worship_team?: string | null; is_student_leader?: number; can_sing?: number };
type Service = { id: string; meeting_id: string; sunday_date: string; service_part: 1 | 2; singer_slots: number; choir_slots: number; leader_type: "student" | "staff"; leader_id: string; special_notes?: string | null; status: string; updated_at?: string };
type Availability = { staff_id: string; present: number; stage_role: "singer" | "session" };
type Assignment = { service_id: string; person_type: "student" | "staff"; person_id: string; name: string; role: "leader" | "singer" | "choir"; side: "left" | "center" | "right"; position_order: number; reason: string };
type ContinuityPerson = { id: string; name: string; service_part: number };
type Override = { id: string; service_id: string; student_id: string; name: string; service_part: number; kind: "department" | "force"; role: "singer" | "choir" | "random" };
type EligibleStudent = { student_id: string; name: string; service_part: number; worship_team: string | null; gender: string | null };
type PoolPerson = { personType: "student" | "staff"; personId: string; name: string };
type StageDragPayload = { source: "stage"; assignment: Assignment } | { source: "pool"; person: PoolPerson };
type StageData = {
  meetings: Meeting[]; services: Service[]; students: Person[]; staff: Person[]; availability: Availability[]; assignments: Assignment[]; overrides: Override[]; eligibleStudents: EligibleStudent[];
  stats: { 1: { attendance: number; eligibleStudents: number }; 2: { attendance: number; eligibleStudents: number }; singerStaff: number; sessionStaff: number };
  continuity: { previousSunday: string | null; priority: ContinuityPerson[]; risks: ContinuityPerson[] };
};

const emptyData: StageData = { meetings: [], services: [], students: [], staff: [], availability: [], assignments: [], overrides: [], eligibleStudents: [], stats: { 1: { attendance: 0, eligibleStudents: 0 }, 2: { attendance: 0, eligibleStudents: 0 }, singerStaff: 0, sessionStaff: 0 }, continuity: { previousSunday: null, priority: [], risks: [] } };
function sundayAfter(date: string) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + 1); return value.toISOString().slice(0, 10); }
function localIso(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function nextSunday() { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() + ((7 - date.getDay()) % 7)); return localIso(date); }
function shortDate(date: string) { const value = new Date(`${date}T00:00:00Z`); return `${value.getUTCMonth() + 1}/${value.getUTCDate()}`; }
function writeStageDrag(event: DragEvent, payload: StageDragPayload) { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", JSON.stringify(payload)); }
function readStageDrag(event: DragEvent) { try { return JSON.parse(event.dataTransfer.getData("text/plain")) as StageDragPayload; } catch { return null; } }

export default function StageClient({ initialTermId = "" }: { initialTermId?: string }) {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] });
  const [termId, setTermId] = useState(initialTermId); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const base = useApi<StageData>(activeId ? `/api/stage?termId=${activeId}` : null, emptyData); const [meetingId, setMeetingId] = useState("");
  const targetSunday = useMemo(() => nextSunday(), []);
  const defaultMeeting = useMemo(() => { const ordered = [...base.data.meetings].sort((a, b) => sundayAfter(a.meeting_date).localeCompare(sundayAfter(b.meeting_date))); return ordered.find((meeting) => sundayAfter(meeting.meeting_date) >= targetSunday) ?? ordered.at(-1); }, [base.data.meetings, targetSunday]);
  const currentMeeting = base.data.meetings.find((item) => item.id === meetingId) ?? defaultMeeting; const sunday = currentMeeting ? sundayAfter(currentMeeting.meeting_date) : "";
  const day = useApi<StageData>(activeId && sunday ? `/api/stage?termId=${activeId}&sundayDate=${sunday}` : null, emptyData); const [message, setMessage] = useState("");
  const act = async (body: Record<string, unknown>) => { try { const send = async (payload: Record<string, unknown>) => { const response = await fetch("/api/stage", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { error?: string; warnings?: string[]; requiresConfirmation?: boolean }; if (!response.ok) { if (result.requiresConfirmation && result.warnings?.length) { const approved = window.confirm(`다음 조건을 확인해주세요.\n\n${result.warnings.map((warning) => `• ${warning}`).join("\n")}\n\n그래도 진행할까요?`); if (approved) return send({ ...payload, force: true }); return { warnings: ["수동 조정을 취소했습니다."] }; } throw new Error(result.error || "요청을 처리하지 못했습니다."); } return result; }; const result = await send(body); setMessage(result.warnings?.join(" ") || "저장했습니다."); await day.reload(); } catch (error) { setMessage((error as Error).message); } };
  const refreshStudentLeaders = async () => { try { const result = await post<{ matched: number; leaders: string[] }>("/api/people", { action: "refresh_student_leaders", kind: "students", termId: activeId }, "PUT"); setMessage(`학생 DB ${result.matched}명을 다시 확인했습니다. 학생 인도자: ${result.leaders.join(", ") || "없음"}`); await day.reload(); } catch (error) { setMessage((error as Error).message); } };

  const availability = useMemo(() => new Map(day.data.availability.map((item) => [item.staff_id, item])), [day.data.availability]);
  const savedLeader = day.data.services.find((service) => service.leader_id); const defaultLeader = day.data.staff.find((staff) => staff.name.replace(/\s/g, "") === "황현민");
  const leaderFallback = savedLeader ? `${savedLeader.leader_type}:${savedLeader.leader_id}` : defaultLeader ? `staff:${defaultLeader.id}` : ""; const leaderKey = `${activeId}:${sunday}`; const [leaderDraft, setLeaderDraft] = useState({ key: "", value: "" }); const leader = leaderDraft.key === leaderKey ? leaderDraft.value : leaderFallback;
  const leaderCandidates = [
    ...day.data.students.filter((student) => student.is_student_leader).map((student) => ({ ...student, type: "student" as const })),
    ...day.data.staff.map((staff) => ({ ...staff, type: "staff" as const })),
  ];
  const saveLeader = () => { const [leaderType, leaderId] = leader.split(":"); return act({ action: "save_leader", termId: activeId, meetingId: currentMeeting?.id, sundayDate: sunday, leaderType, leaderId }); };

  const exportBoard = async (service: Service, pdf: boolean) => {
    await document.fonts.ready; const items = day.data.assignments.filter((item) => item.service_id === service.id); const canvas = document.createElement("canvas"); canvas.width = 1600; canvas.height = 900; const ctx = canvas.getContext("2d"); if (!ctx) return;
    const font = '"Apple SD Gothic Neo","Noto Sans KR",sans-serif'; ctx.fillStyle = "#f6f5ef"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#153f31"; ctx.fillRect(0, 0, canvas.width, 128); ctx.textAlign = "left"; ctx.fillStyle = "#fff"; ctx.font = `700 38px ${font}`; ctx.fillText(`${service.service_part}부 등단표`, 82, 72); ctx.fillStyle = "#cfe0d8"; ctx.font = `500 21px ${font}`; ctx.fillText(service.sunday_date.replaceAll("-", ". "), 82, 104);
    const roundRect = (x: number, y: number, width: number, height: number, radius: number) => { ctx.beginPath(); ctx.roundRect(x, y, width, height, radius); ctx.fill(); ctx.stroke(); };
    const draw = (role: "choir" | "singer", y: number, label: string) => { const left = items.filter((item) => item.role === role && item.side === "left").sort((a, b) => a.position_order - b.position_order); const right = items.filter((item) => item.role === role && item.side === "right").sort((a, b) => a.position_order - b.position_order); ctx.textAlign = "center"; ctx.fillStyle = "#6c7d75"; ctx.font = `700 18px ${font}`; ctx.fillText(label, 800, y - 58); const positions = (list: Assignment[], start: number, end: number) => list.map((_, index) => list.length === 1 ? (start + end) / 2 : start + (end - start) * index / (list.length - 1)); const paint = (list: Assignment[], xs: number[]) => list.forEach((item, index) => { const x = xs[index]; ctx.fillStyle = "#fff"; ctx.strokeStyle = "#cbd4cf"; ctx.lineWidth = 2; roundRect(x - 82, y - 34, 164, 68, 14); ctx.fillStyle = "#17231e"; ctx.font = `700 25px ${font}`; ctx.fillText(item.name, x, y + 9); }); paint(left, positions(left, 130, 650)); paint(right, positions(right, 950, 1470)); };
    draw("choir", 310, "CHOIR"); draw("singer", 535, "SINGER"); const assignedLeader = items.find((item) => item.role === "leader"); if (assignedLeader) { ctx.textAlign = "center"; ctx.fillStyle = "#f3df94"; ctx.strokeStyle = "#b89a35"; ctx.lineWidth = 2; roundRect(700, 708, 200, 76, 18); ctx.fillStyle = "#4b3b0c"; ctx.font = `700 27px ${font}`; ctx.fillText(assignedLeader.name, 800, 756); ctx.fillStyle = "#8b772d"; ctx.font = `700 15px ${font}`; ctx.fillText("인도자", 800, 812); }
    if (pdf) { const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "landscape", unit: "px", format: [1600, 900] }); doc.addImage(canvas.toDataURL("image/png"), "PNG", 0, 0, 1600, 900); doc.save(`${service.sunday_date}-${service.service_part}부-등단표.pdf`); }
    else { const link = document.createElement("a"); link.download = `${service.sunday_date}-${service.service_part}부-등단표.png`; link.href = canvas.toDataURL("image/png"); link.click(); }
  };

  return <main className="manage-content stage-page">{initialTermId && <a className="term-back" href={`/manage/terms/${initialTermId}`}>← 학기 운영 메뉴</a>}<PageTitle eyebrow="05 · STAGE" title="주일 등단 배정" detail="토요 출결과 스탭 참석을 바탕으로 공평하게 배정하고 등단표를 만듭니다." />
    <div className="manage-toolbar">{!initialTermId && <select className="manage-select" value={activeId} onChange={(event) => { setTermId(event.target.value); setMeetingId(""); }}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select>}<label className="manage-field">등단 주일<select className="manage-select" value={currentMeeting?.id ?? ""} onChange={(event) => setMeetingId(event.target.value)}><option value="">토요모임 선택</option>{base.data.meetings.map((meeting) => <option value={meeting.id} key={meeting.id}>{shortDate(meeting.meeting_date)}(토) → {shortDate(sundayAfter(meeting.meeting_date))}(일)</option>)}</select></label></div>
    {message && <Notice error={/부족|않|위험|선택/.test(message)}>{message}</Notice>}
    {!sunday ? <Notice>학기에 등록된 토요모임이 없습니다.</Notice> : <div className="manage-stack stage-workspace" style={{ marginTop: 14 }}>
      <section className="manage-panel stage-day-settings"><div><p className="manage-eyebrow">{shortDate(sunday)} 주일 공통 설정</p><h2>인도자</h2><p>1·2부에 같은 인도자가 들어갑니다. 선택하지 않으면 황현민 스탭이 기본입니다.</p></div><div className="stage-leader-control"><select className="manage-select" value={leader} onChange={(event) => setLeaderDraft({ key: leaderKey, value: event.target.value })}><option value="">인도자 선택</option>{leaderCandidates.map((item) => <option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.name} · {item.type === "student" ? `학생 인도자 ${item.service_part ?? ""}부` : item.name.replace(/\s/g, "") === "황현민" ? "스탭 · 기본" : "스탭"}</option>)}</select><button className="manage-button primary" disabled={!leader} onClick={() => void saveLeader()}>공통 인도자 저장</button></div></section>
      {!day.data.students.some((student) => student.is_student_leader) && <Notice>현재 학기에 지정된 학생 인도자가 없습니다. <button className="manage-inline-button" onClick={() => void refreshStudentLeaders()}>업로드 DB의 ‘인도자 여부’ 다시 읽기</button></Notice>}
      {day.data.continuity.previousSunday && <section className={`manage-alert stage-continuity${day.data.continuity.risks.length ? " error" : ""}`}><b>2주 연속 미등단 검토</b><span>지난주({shortDate(day.data.continuity.previousSunday)}) 미등단 후 이번 주 출석: {day.data.continuity.priority.length ? day.data.continuity.priority.map((item) => `${item.name}(${item.service_part}부)`).join(", ") : "없음"}</span><span>현재 배정에서 다시 빠질 위험: {day.data.continuity.risks.length ? day.data.continuity.risks.map((item) => item.name).join(", ") : "없음"}</span></section>}
      <StageSpecialSettings services={day.data.services} students={day.data.eligibleStudents} overrides={day.data.overrides} act={act} />
      <section className="manage-panel"><div className="stage-section-head"><div><h2>{shortDate(sunday)} 참석 스탭</h2><p>참석할 스탭을 선택한 뒤 그날의 역할을 싱어 또는 세션으로 지정하세요. 이소정 스탭만 기본 세션이고 나머지는 기본 싱어입니다.</p></div></div><div className="stage-staff-grid">{day.data.staff.map((staff) => { const selected = availability.get(staff.id); const isPresent = Boolean(selected?.present); const role = selected?.stage_role ?? (staff.name.replace(/\s/g, "") === "이소정" ? "session" : "singer"); return <article className={`stage-staff-card${isPresent ? " active" : ""}`} key={staff.id}><button type="button" aria-pressed={isPresent} onClick={() => void act({ action: "availability", sundayDate: sunday, staffId: staff.id, present: !isPresent, stageRole: role })}>{isPresent ? "✓" : "+"}</button><b>{staff.name}</b><select aria-label={`${staff.name} 당일 역할`} disabled={!isPresent} value={role} onChange={(event) => void act({ action: "availability", sundayDate: sunday, staffId: staff.id, present: true, stageRole: event.target.value })}><option value="singer">싱어</option><option value="session">세션</option></select></article>; })}</div></section>
      <div className="manage-grid stage-service-grid">{([1, 2] as const).map((part) => { const service = day.data.services.find((item) => item.service_part === part); return <ServiceEditor key={`${part}:${service?.id ?? "new"}`} part={part} termId={activeId} meeting={currentMeeting!} sunday={sunday} leader={leader} data={day.data} act={act} exportBoard={exportBoard} />; })}</div>
    </div>}
  </main>;
}

function StageSpecialSettings({ services, students, overrides, act }: { services: Service[]; students: EligibleStudent[]; overrides: Override[]; act: (body: Record<string, unknown>) => Promise<void> }) {
  const [kind, setKind] = useState<"department" | "force">("department"); const [studentId, setStudentId] = useState(""); const [targetPart, setTargetPart] = useState<1 | 2>(1); const [role, setRole] = useState<"singer" | "choir" | "random">("random");
  const selected = students.find((student) => student.student_id === studentId); const resolvedPart = kind === "department" && selected ? (selected.service_part === 1 ? 2 : 1) : targetPart; const targetService = services.find((service) => service.service_part === resolvedPart);
  const roleLabel = (value: Override["role"]) => value === "singer" ? "싱어" : value === "choir" ? "콰이어" : "기존 규칙에 따라 랜덤";
  return <section className="manage-panel stage-override-box stage-special-settings"><div className="stage-section-head"><div><p className="manage-eyebrow">공통 설정</p><h2>등단 특이사항</h2><p>1·2부 구분 없이 학생을 찾고, 부서 이동 또는 무조건 등단을 지정합니다.</p></div></div><div className="stage-special-controls global"><label className="manage-field">유형<select className="manage-select" value={kind} onChange={(event) => { setKind(event.target.value as "department" | "force"); setStudentId(""); }}><option value="department">부서 이동</option><option value="force">임의 배정 · 무조건 등단</option></select></label><label className="manage-field">학생<select className="manage-select" value={studentId} onChange={(event) => { const value = event.target.value; const student = students.find((item) => item.student_id === value); setStudentId(value); if (student) setTargetPart(student.service_part as 1 | 2); }}><option value="">학생 선택</option>{students.map((student) => <option key={student.student_id} value={student.student_id}>{student.name} · 현재 {student.service_part}부{kind === "department" ? ` → ${student.service_part === 1 ? 2 : 1}부` : ""}</option>)}</select></label>{kind === "force" && <><label className="manage-field">등단 부서<select className="manage-select" value={targetPart} onChange={(event) => setTargetPart(Number(event.target.value) as 1 | 2)}><option value={1}>1부</option><option value={2}>2부</option></select></label><label className="manage-field">역할<select className="manage-select" value={role} onChange={(event) => setRole(event.target.value as "singer" | "choir" | "random")}><option value="random">랜덤 배정</option><option value="singer">싱어</option><option value="choir">콰이어</option></select></label></>}<button className="manage-button" disabled={!studentId || !targetService} onClick={() => void act({ action: "add_override", serviceId: targetService?.id, studentId, overrideKind: kind, role: kind === "department" ? "random" : role })}>특이사항 추가</button></div>{!services.length && <Notice>먼저 1부 또는 2부 인원 설정을 저장해주세요.</Notice>}{overrides.length > 0 && <div className="stage-override-list">{overrides.map((item) => { const service = services.find((candidate) => candidate.id === item.service_id); return <span key={item.id}>{item.kind === "department" ? `${item.name} · ${item.service_part}부 → ${service?.service_part ?? "?"}부` : `${item.name} · ${service?.service_part ?? "?"}부 무조건 등단 · ${roleLabel(item.role)}`}<button title="특이사항 삭제" onClick={() => void act({ action: "remove_override", overrideId: item.id })}>×</button></span>; })}</div>}</section>;
}

function ServiceEditor({ part, termId, meeting, sunday, leader, data, act, exportBoard }: { part: 1 | 2; termId: string; meeting: Meeting; sunday: string; leader: string; data: StageData; act: (body: Record<string, unknown>) => Promise<void>; exportBoard: (service: Service, pdf: boolean) => Promise<void> }) {
  const service = data.services.find((item) => item.service_part === part); const assignments = data.assignments.filter((item) => item.service_id === service?.id); const [singer, setSinger] = useState(service?.singer_slots ?? 6); const [choir, setChoir] = useState(service?.choir_slots ?? 4); const notes = service?.special_notes ?? "";
  const save = () => { const [leaderType, leaderId] = leader.split(":"); return act({ action: "save_config", termId, meetingId: meeting.id, sundayDate: sunday, servicePart: part, singerSlots: singer, choirSlots: choir, leaderType, leaderId, specialNotes: notes }); };
  const side = (role: string, direction: string) => assignments.filter((item) => item.role === role && item.side === direction).sort((a, b) => a.position_order - b.position_order);
  const move = (item: Assignment, change: Partial<Assignment> & { targetPosition?: number }) => act({ action: "move", serviceId: item.service_id, personType: item.person_type, personId: item.person_id, role: change.role ?? item.role, side: change.side ?? item.side, targetPosition: change.targetPosition });
  const add = (person: PoolPerson, role: "singer" | "choir", direction: "left" | "right", targetPosition: number) => act({ action: "add_manual", serviceId: service?.id, personType: person.personType, personId: person.personId, role, side: direction, targetPosition });
  const remove = (item: Assignment) => act({ action: "remove_assignment", serviceId: item.service_id, personType: item.person_type, personId: item.person_id });
  const overrideByStudent = new Map(data.overrides.map((item) => [item.student_id, item])); const assignedStudentIds = new Set(data.assignments.filter((item) => item.person_type === "student").map((item) => item.person_id));
  const classWorship = data.eligibleStudents.filter((student) => { const override = overrideByStudent.get(student.student_id); return (override ? override.service_id === service?.id : student.service_part === part) && !assignedStudentIds.has(student.student_id); }).map((student) => ({ personType: "student" as const, personId: student.student_id, name: student.name }));
  const assignedStaffIds = new Set(assignments.filter((item) => item.person_type === "staff").map((item) => item.person_id)); const presentSingerStaffIds = new Set(data.availability.filter((item) => item.present && item.stage_role === "singer").map((item) => item.staff_id));
  const offstageStaff = data.staff.filter((staff) => presentSingerStaffIds.has(staff.id) && !assignedStaffIds.has(staff.id) && staff.id !== assignments.find((item) => item.role === "leader" && item.person_type === "staff")?.person_id).map((staff) => ({ personType: "staff" as const, personId: staff.id, name: staff.name }));
  return <section className="manage-panel manage-stack stage-service"><div className="stage-section-head"><h2>{part}부 <span className="manage-badge">{service?.status ?? "미설정"}</span></h2><div className="stage-service-stats"><b>토요 출석 {data.stats[part].attendance}명</b><b>등단 대상 학생 {data.stats[part].eligibleStudents}명</b><b>참석 싱어 스탭 {data.stats.singerStaff}명</b></div></div>
    <div className="manage-grid"><label className="manage-field">싱어<input className="manage-input" type="number" min="0" value={singer} onChange={(event) => setSinger(Number(event.target.value))} /></label><label className="manage-field">콰이어<input className="manage-input" type="number" min="0" value={choir} onChange={(event) => setChoir(Number(event.target.value))} /></label></div><div className="manage-toolbar"><button className="manage-button" disabled={!leader} onClick={() => void save()}>설정 저장</button><button className="manage-button primary" disabled={!service} onClick={() => void act({ action: "generate", serviceId: service?.id })}>자동 배정</button><button className="manage-button" disabled={!service || !assignments.length} onClick={() => void act({ action: "confirm", serviceId: service?.id })}>확정</button></div>
    {service && assignments.length > 0 && <><div className="stage-editor-layout"><div className="stage-board"><div className="stage-label">콰이어</div><StageRow serviceId={service.id} stageRole="choir" left={side("choir", "left")} right={side("choir", "right")} move={move} add={add} remove={remove} /><div className="stage-label">싱어</div><StageRow serviceId={service.id} stageRole="singer" left={side("singer", "left")} right={side("singer", "right")} move={move} add={add} remove={remove} /><div className="stage-row"><div /><div className="stage-person leader">{assignments.find((item) => item.role === "leader")?.name}</div><div /></div></div><StageOffstage serviceId={service.id} students={classWorship} staff={offstageStaff} remove={remove} /></div><div className="manage-toolbar"><button className="manage-button" onClick={() => void exportBoard(service, false)}>PNG 저장</button><button className="manage-button" onClick={() => void exportBoard(service, true)}>PDF 저장</button></div></>}
  </section>;
}

function StageRow({ serviceId, stageRole, left, right, move, add, remove }: { serviceId: string; stageRole: "singer" | "choir"; left: Assignment[]; right: Assignment[]; move: (item: Assignment, change: Partial<Assignment> & { targetPosition?: number }) => Promise<void>; add: (person: PoolPerson, role: "singer" | "choir", direction: "left" | "right", targetPosition: number) => Promise<void>; remove: (item: Assignment) => Promise<void> }) {
  const dropped = (event: DragEvent, side: "left" | "right", targetPosition: number) => { event.preventDefault(); event.stopPropagation(); const payload = readStageDrag(event); if (!payload) return; if (payload.source === "stage") { if (payload.assignment.service_id !== serviceId) return; void move(payload.assignment, { role: stageRole, side, targetPosition }); } else if (payload.person.personType !== "staff" || stageRole === "singer") void add(payload.person, stageRole, side, targetPosition); };
  const person = (item: Assignment) => <div className="stage-person draggable" draggable title={item.reason} onDragStart={(event) => writeStageDrag(event, { source: "stage", assignment: item })} onDragOver={(event) => event.preventDefault()} onDrop={(event) => dropped(event, item.side as "left" | "right", item.position_order)} key={`${item.person_type}:${item.person_id}`}><b>{item.name}</b><button className="stage-remove-person" aria-label={`${item.name} 등단에서 빼기`} title="등단에서 빼기" onClick={() => void remove(item)}>×</button></div>;
  const side = (items: Assignment[], direction: "left" | "right") => <div className="stage-side drop-zone" onDragOver={(event) => event.preventDefault()} onDrop={(event) => dropped(event, direction, items.length)}>{items.map(person)}{!items.length && <span className="stage-empty-drop">여기에 놓기</span>}</div>;
  return <div className="stage-row">{side(left, "left")}<div />{side(right, "right")}</div>;
}

function StageOffstage({ serviceId, students, staff, remove }: { serviceId: string; students: PoolPerson[]; staff: PoolPerson[]; remove: (item: Assignment) => Promise<void> }) {
  const dropped = (event: DragEvent, personType: "student" | "staff") => { event.preventDefault(); const payload = readStageDrag(event); if (payload?.source === "stage" && payload.assignment.service_id === serviceId && payload.assignment.person_type === personType) void remove(payload.assignment); };
  const panel = (title: string, personType: "student" | "staff", people: PoolPerson[]) => <section className="stage-offstage-panel" onDragOver={(event) => event.preventDefault()} onDrop={(event) => dropped(event, personType)}><div className="stage-offstage-head"><b>{title}</b><span>{people.length}명</span></div><div className="stage-offstage-list">{people.map((person) => <div className="stage-pool-person" draggable onDragStart={(event) => writeStageDrag(event, { source: "pool", person })} key={`${person.personType}:${person.personId}`}>{person.name}</div>)}{!people.length && <span className="stage-offstage-empty">없음</span>}</div></section>;
  return <aside className="stage-offstage">{panel("반에서 예배하기", "student", students)}{panel("등단하지 않는 스탭", "staff", staff)}</aside>;
}
