"use client";
import { useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";
type Term = { id: string; name: string; status: string }; type Meeting = { id: string; meeting_date: string }; type Person = { id: string; name: string; is_student_leader?: number; can_sing?: number }; type Service = { id: string; meeting_id: string; sunday_date: string; service_part: 1 | 2; singer_slots: number; choir_slots: number; leader_type: "student" | "staff"; leader_id: string; status: string; updated_at?: string }; type Assignment = { service_id: string; person_type: "student" | "staff"; person_id: string; name: string; role: "leader" | "singer" | "choir"; side: "left" | "center" | "right"; position_order: number; reason: string };
type StageData = { meetings: Meeting[]; services: Service[]; students: Person[]; staff: Person[]; availability: Array<{ staff_id: string; present: number }>; assignments: Assignment[] };
function sundayAfter(date: string) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + 1); return value.toISOString().slice(0, 10); }

export default function StageClient() {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] }); const [termId, setTermId] = useState(""); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const base = useApi<StageData>(activeId ? `/api/stage?termId=${activeId}` : null, { meetings: [], services: [], students: [], staff: [], availability: [], assignments: [] }); const [meetingId, setMeetingId] = useState(""); const currentMeeting = base.data.meetings.find((item) => item.id === meetingId) ?? base.data.meetings[0]; const sunday = currentMeeting ? sundayAfter(currentMeeting.meeting_date) : "";
  const day = useApi<StageData>(activeId && sunday ? `/api/stage?termId=${activeId}&sundayDate=${sunday}` : null, { meetings: [], services: [], students: [], staff: [], availability: [], assignments: [] }); const [message, setMessage] = useState("");
  const present = new Set(day.data.availability.filter((item) => item.present).map((item) => item.staff_id));
  const act = async (body: Record<string, unknown>) => { try { const result = await post<{ warnings?: string[] }>("/api/stage", body); setMessage(result.warnings?.join(" ") || "저장했습니다."); await day.reload(); } catch (error) { setMessage((error as Error).message); } };
  const exportBoard = async (service: Service, pdf: boolean) => { const items = day.data.assignments.filter((item) => item.service_id === service.id); const canvas = document.createElement("canvas"); canvas.width = 1400; canvas.height = 760; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.fillStyle = "#17201c"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#fff"; ctx.font = "bold 42px sans-serif"; ctx.textAlign = "center"; ctx.fillText(`${service.sunday_date} · ${service.service_part}부 등단표`, 700, 70); const draw = (role: string, y: number) => { const left = items.filter((i) => i.role === role && i.side === "left"); const right = items.filter((i) => i.role === role && i.side === "right"); const paint = (list: Assignment[], start: number, direction: number) => list.forEach((item, index) => { const x = start + index * 170 * direction; ctx.strokeStyle = "#7d8d84"; ctx.strokeRect(x - 65, y - 30, 130, 60); ctx.font = "25px sans-serif"; ctx.fillText(item.name, x, y + 9); }); paint(left, 580, -1); paint(right, 820, 1); }; draw("choir", 240); draw("singer", 430); const leader = items.find((i) => i.role === "leader"); if (leader) { ctx.strokeStyle = "#e3c76c"; ctx.strokeRect(630, 590, 140, 70); ctx.fillStyle = "#ffe38a"; ctx.fillText(leader.name, 700, 636); } if (pdf) { const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "landscape", unit: "px", format: [1400, 760] }); doc.addImage(canvas.toDataURL("image/png"), "PNG", 0, 0, 1400, 760); doc.save(`${service.sunday_date}-${service.service_part}부-등단표.pdf`); } else { const link = document.createElement("a"); link.download = `${service.sunday_date}-${service.service_part}부-등단표.png`; link.href = canvas.toDataURL("image/png"); link.click(); } };
  return <main className="manage-content"><PageTitle eyebrow="05 · STAGE" title="주일 등단 배정" detail="토요 출결과 스탭 참석을 바탕으로 공평하게 배정하고 등단표를 만듭니다." />
    <div className="manage-toolbar"><select className="manage-select" value={activeId} onChange={(event) => { setTermId(event.target.value); setMeetingId(""); }}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select><select className="manage-select" value={currentMeeting?.id ?? ""} onChange={(event) => setMeetingId(event.target.value)}><option value="">토요모임 선택</option>{base.data.meetings.map((meeting) => <option value={meeting.id} key={meeting.id}>{meeting.meeting_date} → {sundayAfter(meeting.meeting_date)}</option>)}</select></div>
    {message && <Notice error={message.includes("부족") || message.includes("않")}>{message}</Notice>}{sunday && <div className="manage-stack" style={{ marginTop: 14 }}>
      <section className="manage-panel"><h2>{sunday} 참석 스탭</h2><div className="manage-toolbar">{day.data.staff.map((staff) => <button className={`manage-button${present.has(staff.id) ? " primary" : ""}`} key={staff.id} onClick={() => void act({ action: "availability", sundayDate: sunday, staffId: staff.id, present: !present.has(staff.id) })}>{staff.name}</button>)}</div></section>
      <div className="manage-grid">{([1, 2] as const).map((part) => { const service = day.data.services.find((item) => item.service_part === part); return <ServiceEditor key={`${part}:${service?.id ?? "new"}:${service?.updated_at ?? ""}`} part={part} termId={activeId} meeting={currentMeeting} sunday={sunday} data={day.data} act={act} exportBoard={exportBoard} />; })}</div>
    </div>}
  </main>;
}

function ServiceEditor({ part, termId, meeting, sunday, data, act, exportBoard }: { part: 1 | 2; termId: string; meeting: Meeting; sunday: string; data: StageData; act: (body: Record<string, unknown>) => Promise<void>; exportBoard: (service: Service, pdf: boolean) => Promise<void> }) {
  const service = data.services.find((item) => item.service_part === part); const assignments = data.assignments.filter((item) => item.service_id === service?.id); const [singer, setSinger] = useState(service?.singer_slots ?? 6); const [choir, setChoir] = useState(service?.choir_slots ?? 4); const [leader, setLeader] = useState(service ? `${service.leader_type}:${service.leader_id}` : "");
  const candidates = [...data.students.filter((item) => item.is_student_leader).map((item) => ({ ...item, type: "student" })), ...data.staff.filter((item) => item.can_sing).map((item) => ({ ...item, type: "staff" }))];
  const save = () => { const [leaderType, leaderId] = leader.split(":"); return act({ action: "save_config", termId, meetingId: meeting.id, sundayDate: sunday, servicePart: part, singerSlots: singer, choirSlots: choir, leaderType, leaderId }); };
  const side = (role: string, direction: string) => assignments.filter((item) => item.role === role && item.side === direction).sort((a, b) => a.position_order - b.position_order);
  const move = (item: Assignment, change: Partial<Assignment>) => act({ action: "move", serviceId: item.service_id, personType: item.person_type, personId: item.person_id, role: change.role ?? item.role, side: change.side ?? item.side, positionOrder: item.position_order });
  return <section className="manage-panel manage-stack"><h2>{part}부 <span className="manage-badge">{service?.status ?? "미설정"}</span></h2><div className="manage-grid"><label className="manage-field">싱어<input className="manage-input" type="number" min="0" value={singer} onChange={(event) => setSinger(Number(event.target.value))} /></label><label className="manage-field">콰이어<input className="manage-input" type="number" min="0" value={choir} onChange={(event) => setChoir(Number(event.target.value))} /></label></div><label className="manage-field">인도자<select className="manage-select" value={leader} onChange={(event) => setLeader(event.target.value)}><option value="">선택</option>{candidates.map((item) => <option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.name} · {item.type === "student" ? "학생 인도" : "싱어 스탭"}</option>)}</select></label><div className="manage-toolbar"><button className="manage-button" onClick={() => void save()}>설정 저장</button><button className="manage-button primary" disabled={!service} onClick={() => void act({ action: "generate", serviceId: service?.id })}>자동 배정</button><button className="manage-button" disabled={!service || !assignments.length} onClick={() => void act({ action: "confirm", serviceId: service?.id })}>확정</button></div>
    {service && assignments.length > 0 && <><div className="stage-board"><div className="stage-label">콰이어</div><StageRow left={side("choir", "left")} right={side("choir", "right")} move={move} /><div className="stage-label">싱어</div><StageRow left={side("singer", "left")} right={side("singer", "right")} move={move} /><div className="stage-row"><div /><div className="stage-person leader">{assignments.find((item) => item.role === "leader")?.name}</div><div /></div></div><div className="manage-toolbar"><button className="manage-button" onClick={() => void exportBoard(service, false)}>PNG 저장</button><button className="manage-button" onClick={() => void exportBoard(service, true)}>PDF 저장</button></div></>}
  </section>;
}
function StageRow({ left, right, move }: { left: Assignment[]; right: Assignment[]; move: (item: Assignment, change: Partial<Assignment>) => Promise<void> }) { const person = (item: Assignment) => <div className="stage-person" title={item.reason} key={`${item.person_type}:${item.person_id}`}><b>{item.name}</b><br /><button title="반대편으로 이동" onClick={() => void move(item, { side: item.side === "left" ? "right" : "left" })}>↔</button><select value={item.role} onChange={(event) => void move(item, { role: event.target.value as Assignment["role"] })}><option value="singer">싱어</option><option value="choir">콰이어</option></select></div>; return <div className="stage-row"><div className="stage-side">{left.map(person)}</div><div /><div className="stage-side">{right.map(person)}</div></div>; }
