"use client";
import { useState } from "react";
import { api, Notice, PageTitle, post, useApi } from "../_components/shared";

type Person = Record<string, string | number | null> & { id: string; name: string };
type Preview = { kind: "students" | "staff"; filename: string; objectKey: string; headers: string[]; mapping: Record<string, string>; rows: Array<Record<string, unknown> & { rowNumber: number; name: string; duplicate: boolean; errors: string[] }>; summary: { total: number; errors: number; duplicates: number } };
type Data = { students: Person[]; staff: Person[]; imports: Array<Record<string, string | number>>; users: Array<Record<string, string | null>>; role: string };

export default function PeopleClient() {
  const state = useApi<Data>("/api/people", { students: [], staff: [], imports: [], users: [], role: "staff" });
  const [tab, setTab] = useState<"students" | "staff">("students"); const [preview, setPreview] = useState<Preview | null>(null); const [sourceFile, setSourceFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const upload = async (file: File | undefined, mapping?: Record<string, string>) => { if (!file) return; setSourceFile(file); setBusy(true); setMessage(""); try { const form = new FormData(); form.set("kind", tab); form.set("file", file); if (mapping) { form.set("mapping", JSON.stringify(mapping)); if (preview?.objectKey) form.set("objectKey", preview.objectKey); } setPreview(await api<Preview>("/api/people", { method: "POST", body: form })); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const confirm = async () => { if (!preview) return; setBusy(true); try { const result = await post<{ imported: number; skipped: number }>("/api/people", { ...preview, allowDuplicates: false }, "PUT"); setMessage(`${result.imported}명 저장 · ${result.skipped}행 보류`); setPreview(null); await state.reload(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } };
  const authorize = async (user: Record<string, string | null>, changes: Record<string, string | null>) => { await post("/api/people", { action: "authorize_user", kind: "staff", userId: user.id, role: user.role, status: "active", staffId: user.staff_id, ...changes }, "PUT"); await state.reload(); };
  const people = state.data[tab];
  return <main className="manage-content"><PageTitle eyebrow="01 · PEOPLE" title="인원 DB" detail="학생과 스탭 파일을 검토한 뒤 확정 저장합니다." />
    <div className="manage-tabs"><button className={tab === "students" ? "active" : ""} onClick={() => { setTab("students"); setPreview(null); }}>학생 {state.data.students.length}</button><button className={tab === "staff" ? "active" : ""} onClick={() => { setTab("staff"); setPreview(null); }}>스탭 {state.data.staff.length}</button></div>
    <div className="manage-stack">
      {state.data.role === "admin" && <section className="manage-panel"><div className="manage-toolbar"><label className="manage-button primary">{busy ? "분석 중…" : `${tab === "students" ? "학생" : "스탭"} CSV·XLSX 선택`}<input hidden type="file" accept=".csv,.xlsx,.xls" onChange={(event) => void upload(event.target.files?.[0])} /></label><span>열 이름은 이름·학년·예배부서·학생인도자 또는 이메일·역할·싱어가능·조담당가능을 인식합니다.</span></div>{message && <Notice error={message.includes("못") || message.includes("오류")}>{message}</Notice>}
      {preview && <div className="manage-stack"><Notice>{preview.filename} · 전체 {preview.summary.total}행 · 오류 {preview.summary.errors} · 중복 후보 {preview.summary.duplicates}</Notice><div className="manage-toolbar">{(tab === "students" ? [["name","이름"],["grade","학년"],["gender","성별"],["servicePart","예배 부서"],["isStudentLeader","학생 인도자"],["notes","비고"]] : [["name","이름"],["email","이메일"],["duty","역할"],["canSing","싱어 가능"],["canLeadGroup","조 담당 가능"],["preferredService","선호 예배"],["notes","비고"]]).map(([field,label]) => <label className="manage-field" key={field}>{label}<select className="manage-select" value={preview.mapping[field] ?? ""} onChange={(event) => setPreview({ ...preview, mapping: { ...preview.mapping, [field]: event.target.value } })}><option value="">자동/미사용</option>{preview.headers.map((header) => <option value={header} key={header}>{header}</option>)}</select></label>)}<button className="manage-button" disabled={!sourceFile} onClick={() => void upload(sourceFile ?? undefined, preview.mapping)}>열 매핑 적용</button></div><div className="manage-table-wrap"><table className="manage-table"><thead><tr><th>행</th><th>이름</th><th>예배/역할</th><th>검토</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.name || "—"}</td><td>{String(row.servicePart ?? row.duty ?? "—")}</td><td>{row.errors.length ? <span className="manage-badge warn">{row.errors.join(" ")}</span> : row.duplicate ? <span className="manage-badge warn">동명이인·중복 확인</span> : <span className="manage-badge">저장 가능</span>}</td></tr>)}</tbody></table></div><button className="manage-button primary" disabled={busy || preview.rows.every((row) => row.errors.length > 0 || row.duplicate)} onClick={() => void confirm()}>오류·중복 제외하고 확정 저장</button></div>}</section>}
      <section className="manage-panel"><div className="manage-table-wrap"><table className="manage-table"><thead><tr><th>이름</th><th>{tab === "students" ? "학년" : "역할"}</th><th>{tab === "students" ? "예배" : "가능 업무"}</th><th>상태</th></tr></thead><tbody>{people.map((person) => <tr key={person.id}><td>{person.name}</td><td>{tab === "students" ? person.grade || "—" : person.duty || "—"}</td><td>{tab === "students" ? `${person.service_part}부${person.is_student_leader ? " · 학생 인도" : ""}` : `${person.can_sing ? "싱어 " : ""}${person.can_lead_group ? "조 담당" : ""}` || "일반"}</td><td><span className="manage-badge">{person.active ? "활성" : "중지"}</span></td></tr>)}</tbody></table>{!state.loading && !people.length && <Notice>등록된 인원이 없습니다. 위에서 파일을 선택해주세요.</Notice>}</div></section>
      {state.data.role === "admin" && state.data.users.length > 0 && <section className="manage-panel"><h2>로그인 계정 승인</h2><div className="manage-list">{state.data.users.map((user) => <div className="manage-person" key={user.id}><div><b>{user.display_name}</b><br /><small>{user.email} · {user.status}</small></div><div className="manage-toolbar"><select className="manage-select" value={user.staff_id ?? ""} onChange={(event) => void authorize(user, { staffId: event.target.value || null })}><option value="">스탭 연결 안 함</option>{state.data.staff.map((staff) => <option value={staff.id} key={staff.id}>{staff.name}</option>)}</select><select className="manage-select" value={user.role ?? "staff"} onChange={(event) => void authorize(user, { role: event.target.value })}><option value="admin">관리자</option><option value="group_staff">조 담당 스탭</option><option value="staff">일반 스탭</option></select><button className="manage-button" onClick={() => void authorize(user, { status: user.status === "active" ? "disabled" : "active" })}>{user.status === "active" ? "중지" : "승인"}</button></div></div>)}</div></section>}
    </div>
  </main>;
}
