"use client";
import { Fragment, useMemo, useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";

type Term = { id: string; name: string; status: string };
type Meeting = { id: string; meeting_date: string; kind: "regular" | "extra" | "break"; title?: string | null };
type Group = { id: string; name: string; staff_names: string };
type Student = { group_id: string; student_id: string; name: string; grade: number | null; service_part: number };
type Row = Student & { meeting_id: string; status: string };
type EditableStatus = "present" | "late" | "absent" | "unset";
type AttendanceData = { meetings: Meeting[]; groups: Group[]; students: Student[]; rows: Row[]; summary: { total: number; unset: number } };
const emptyData: AttendanceData = { meetings: [], groups: [], students: [], rows: [], summary: { total: 0, unset: 0 } };
const options = [["present", "출석"], ["late", "지각"], ["absent", "결석"]] as const;
const editableStatus = (status?: string): EditableStatus => options.some(([value]) => value === status) ? status as Exclude<EditableStatus, "unset"> : "unset";

export default function AttendanceClient({ initialTermId = "", initialMeetingId = "" }: { initialTermId?: string; initialMeetingId?: string }) {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] }); const [termId, setTermId] = useState(initialTermId); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const state = useApi<AttendanceData>(activeId ? `/api/attendance?termId=${activeId}` : null, emptyData); const [message, setMessage] = useState(""); const [selectedGroupId, setSelectedGroupId] = useState("");
  const rowMap = useMemo(() => new Map(state.data.rows.map((row) => [`${row.student_id}:${row.meeting_id}`, row])), [state.data.rows]);
  const visibleMeetings = state.data.meetings;
  const activeGroupId = state.data.groups.some((group) => group.id === selectedGroupId) ? selectedGroupId : state.data.groups[0]?.id ?? "";
  const visibleGroups = useMemo(() => state.data.groups.filter((group) => group.id === activeGroupId), [activeGroupId, state.data.groups]);
  const selectedUnset = useMemo(() => state.data.rows.filter((row) => row.group_id === activeGroupId && row.status === "unset").length, [activeGroupId, state.data.rows]);
  const months = useMemo(() => { const result: Array<{ key: string; label: string; meetings: Meeting[] }> = []; for (const meeting of visibleMeetings) { const [year, month] = meeting.meeting_date.split("-"); const key = `${year}-${month}`; const current = result.at(-1); if (current?.key === key) current.meetings.push(meeting); else result.push({ key, label: `${Number(month)}월`, meetings: [meeting] }); } return result; }, [visibleMeetings]);
  const save = async (student: Student, meeting: Meeting, status: EditableStatus) => {
    const key = `${student.student_id}:${meeting.id}`; const previous = rowMap.get(key); const wasUnset = previous?.status === "unset"; const willUnset = status === "unset"; setMessage("");
    state.setData({ ...state.data, rows: state.data.rows.map((row) => row.student_id === student.student_id && row.meeting_id === meeting.id ? { ...row, status } : row), summary: { ...state.data.summary, unset: Math.max(0, state.data.summary.unset + Number(willUnset) - Number(wasUnset)) } });
    try { await post("/api/attendance", { meetingId: meeting.id, studentId: student.student_id, status }); } catch (error) { setMessage((error as Error).message); state.setData({ ...state.data, rows: state.data.rows.map((row) => row.student_id === student.student_id && row.meeting_id === meeting.id ? { ...row, status: previous?.status ?? "unset" } : row) }); }
  };

  return <main className="manage-content attendance-page">{initialTermId && <a className="term-back" href={initialMeetingId ? `/manage/weeks/${initialMeetingId}` : `/manage/terms/${initialTermId}`}>← {initialMeetingId ? "주차 메뉴" : "학기 운영 메뉴"}</a>}<PageTitle eyebrow="04 · ATTENDANCE" title="토요모임 출결" detail="학생과 날짜가 만나는 칸에서 출석·지각·결석을 바로 선택합니다." />
    <div className="attendance-toolbar">{!initialTermId && <select className="manage-select" value={activeId} onChange={(event) => { setTermId(event.target.value); setSelectedGroupId(""); }}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select>}{state.data.groups.length > 0 && <label className="attendance-group-select"><span>담당 조</span><select className="manage-select" value={activeGroupId} onChange={(event) => setSelectedGroupId(event.target.value)}>{state.data.groups.map((group) => <option value={group.id} key={group.id}>{group.name} · 담당 {group.staff_names || "미배정"}</option>)}</select></label>}<div className="attendance-legend"><span className="present">출석</span><span className="late">지각</span><span className="absent">결석</span><span className="break">휴강</span></div><span className={`manage-badge${selectedUnset ? " warn" : ""}`}>이 조 미입력 {selectedUnset}칸</span></div>
    {message && <Notice error>{message}</Notice>}{!activeId ? <Notice>먼저 학기를 선택해주세요.</Notice> : state.loading ? <Notice>출결표를 불러오는 중입니다.</Notice> : !visibleMeetings.length ? <Notice>출결을 입력할 모임 날짜가 없습니다.</Notice> : !state.data.groups.length || !state.data.students.length ? <Notice>담당 조에 편성된 학생이 없습니다.</Notice> : <div className="attendance-table-shell"><table className="attendance-matrix"><thead><tr><th className="attendance-number" rowSpan={2}>순</th><th className="attendance-name" rowSpan={2}>학생</th>{months.map((month) => <th className="attendance-month" colSpan={month.meetings.length} key={month.key}>{month.label}</th>)}</tr><tr>{visibleMeetings.map((meeting) => <th className={`attendance-date${meeting.kind === "break" ? " break" : ""}`} key={meeting.id}><b>{Number(meeting.meeting_date.slice(8, 10))}</b><small>{meeting.kind === "break" ? "휴강" : "토"}</small></th>)}</tr></thead><tbody>{visibleGroups.map((group) => { const students = state.data.students.filter((student) => student.group_id === group.id); if (!students.length) return null; return <Fragment key={group.id}><tr className="attendance-group-row"><th colSpan={visibleMeetings.length + 2}>{group.name}<span>담당 {group.staff_names || "미배정"} · 학생 {students.length}명</span></th></tr>{students.map((student, index) => <tr key={student.student_id}><td className="attendance-number">{index + 1}</td><th className="attendance-name"><b>{student.name}</b><small>{student.grade ?? "?"}학년</small></th>{visibleMeetings.map((meeting) => { if (meeting.kind === "break") return <td className="attendance-cell break" key={meeting.id}><span>휴강</span></td>; const row = rowMap.get(`${student.student_id}:${meeting.id}`); const status = editableStatus(row?.status); return <td className={`attendance-cell ${status}`} key={meeting.id}><select aria-label={`${student.name} ${meeting.meeting_date} 출결`} value={status} onChange={(event) => void save(student, meeting, event.target.value as EditableStatus)}><option value="unset">·</option>{options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></td>; })}</tr>)}</Fragment>; })}</tbody></table></div>}
  </main>;
}
