"use client";
import { useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";
type Term = { id: string; name: string; status: string }; type Meeting = { id: string; meeting_date: string }; type Group = { id: string; name: string }; type Row = { group_id: string; student_id: string; name: string; grade: number; status: string; note: string };
const options = [["present", "출"], ["late", "지"], ["left_early", "조"], ["absent", "결"], ["excused", "연"], ["unset", "—"]];
export default function AttendanceClient({ initialTermId = "" }: { initialTermId?: string }) {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] }); const [termId, setTermId] = useState(initialTermId); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const meetingList = useApi<{ meetings: Meeting[]; groups: Group[]; rows: Row[]; summary: { total: number; unset: number } }>(activeId ? `/api/attendance?termId=${activeId}` : null, { meetings: [], groups: [], rows: [], summary: { total: 0, unset: 0 } }); const [meetingId, setMeetingId] = useState(""); const selectedMeeting = meetingId || meetingList.data.meetings[0]?.id || "";
  const rowsState = useApi<{ meetings: Meeting[]; groups: Group[]; rows: Row[]; summary: { total: number; unset: number } }>(activeId && selectedMeeting ? `/api/attendance?termId=${activeId}&meetingId=${selectedMeeting}` : null, { meetings: [], groups: [], rows: [], summary: { total: 0, unset: 0 } }); const [message, setMessage] = useState("");
  const save = async (row: Row, status: string) => { rowsState.setData({ ...rowsState.data, rows: rowsState.data.rows.map((item) => item.student_id === row.student_id ? { ...item, status } : item) }); try { await post("/api/attendance", { meetingId: selectedMeeting, studentId: row.student_id, status, note: row.note }); } catch (error) { setMessage((error as Error).message); await rowsState.reload(); } };
  return <main className="manage-content">{initialTermId && <a className="term-back" href={`/manage/terms/${initialTermId}`}>← 학기 운영 메뉴</a>}<PageTitle eyebrow="04 · ATTENDANCE" title="토요모임 출결" detail="조 담당 스탭은 자신의 조만, 관리자는 모든 조를 입력합니다." />
    <div className="manage-toolbar">{!initialTermId && <select className="manage-select" value={activeId} onChange={(event) => { setTermId(event.target.value); setMeetingId(""); }}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select>}<select className="manage-select" value={selectedMeeting} onChange={(event) => setMeetingId(event.target.value)}><option value="">모임 선택</option>{meetingList.data.meetings.map((meeting) => <option value={meeting.id} key={meeting.id}>{meeting.meeting_date}</option>)}</select><span className={`manage-badge${rowsState.data.summary.unset ? " warn" : ""}`}>미입력 {rowsState.data.rows.filter((row) => row.status === "unset").length}명</span></div>
    {message && <Notice error>{message}</Notice>}{!selectedMeeting ? <Notice>출결을 입력할 모임을 선택해주세요.</Notice> : <div className="manage-stack">{rowsState.data.groups.map((group) => <section className="manage-panel" key={group.id}><h2>{group.name}</h2>{rowsState.data.rows.filter((row) => row.group_id === group.id).map((row) => <div className="attendance-row" key={row.student_id}><div><b>{row.name}</b><br /><small>{row.grade || "?"}학년</small></div>{options.map(([status, label]) => <button key={status} className={row.status === status ? "active" : ""} title={status} onClick={() => void save(row, status)}>{label}</button>)}</div>)}</section>)}</div>}
  </main>;
}
