"use client";
import { useMemo, useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";
type Term = { id: string; name: string; status: string }; type Group = { id: string; name: string; capacity: number; required_staff: number; status: string }; type Student = { id: string; name: string; grade: number; gender: string; service_part: number }; type Staff = { id: string; name: string; can_lead_group: number }; type Member = { group_id: string; student_id: string; name: string }; type AssignedStaff = { group_id: string; staff_id: string; name: string }; type Constraint = { id: string; type: string; student_a_id: string; student_b_id: string };
type GroupData = { groups: Group[]; members: Member[]; assignedStaff: AssignedStaff[]; constraints: Constraint[]; students: Student[]; staff: Staff[] };

export default function GroupsClient() {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] }); const [termId, setTermId] = useState(""); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const groups = useApi<GroupData>(activeId ? `/api/groups?termId=${activeId}` : null, { groups: [], members: [], assignedStaff: [], constraints: [], students: [], staff: [] }); const [message, setMessage] = useState(""); const [dragId, setDragId] = useState("");
  const assignedIds = new Set(groups.data.members.map((item) => item.student_id)); const unassigned = groups.data.students.filter((student) => !assignedIds.has(student.id)); const names = useMemo(() => new Map(groups.data.students.map((student) => [student.id, student.name])), [groups.data.students]);
  const act = async (body: Record<string, unknown>) => { try { const result = await post<{ warnings?: string[] }>("/api/groups", { ...body, termId: activeId }); setMessage(result.warnings?.join(" ") || "저장했습니다."); await groups.reload(); } catch (error) { setMessage((error as Error).message); } };
  const configure = (form: FormData) => act({ action: "configure", count: form.get("count"), capacity: form.get("capacity"), requiredStaff: form.get("staff") });
  const constraint = (form: FormData) => act({ action: "add_constraint", type: form.get("type"), studentAId: form.get("a"), studentBId: form.get("b") });
  const drop = (groupId: string | null) => { if (dragId) void act({ action: "assign_student", studentId: dragId, groupId }); setDragId(""); };
  return <main className="manage-content"><PageTitle eyebrow="03 · GROUP" title="조 편성" detail="관계 조건을 지키며 자동 편성하고, 드래그로 조정한 뒤 확정합니다." action={<select className="manage-select" value={activeId} onChange={(event) => setTermId(event.target.value)}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select>} />
    {!activeId ? <Notice>먼저 학기를 생성해주세요.</Notice> : <div className="manage-stack">
      <div className="manage-grid"><form className="manage-panel manage-toolbar" action={(form) => void configure(form)}><label className="manage-field">조 수<input className="manage-input" name="count" type="number" min="1" defaultValue="4" /></label><label className="manage-field">조 정원<input className="manage-input" name="capacity" type="number" min="1" defaultValue="8" /></label><label className="manage-field">담당 스탭/조<input className="manage-input" name="staff" type="number" min="0" defaultValue="1" /></label><button className="manage-button primary">초안 만들기</button></form>
      <form className="manage-panel manage-toolbar" action={(form) => void constraint(form)}><select className="manage-select" name="type"><option value="together">같은 조</option><option value="apart">다른 조</option></select><select className="manage-select" name="a" required><option value="">학생 A</option>{groups.data.students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select><select className="manage-select" name="b" required><option value="">학생 B</option>{groups.data.students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select><button className="manage-button">조건 추가</button><div>{groups.data.constraints.map((item) => <span className={`manage-badge${item.type === "apart" ? " warn" : ""}`} key={item.id}>{names.get(item.student_a_id)} · {names.get(item.student_b_id)} {item.type === "together" ? "같이" : "분리"}</span>)}</div></form></div>
      {message && <Notice error={message.includes("없") || message.includes("초과") || message.includes("부족")}>{message}</Notice>}
      <div className="manage-toolbar"><button className="manage-button primary" disabled={!groups.data.groups.length} onClick={() => void act({ action: "auto", seed: Date.now() % 100000 })}>자동 편성안 생성</button><button className="manage-button" disabled={!groups.data.groups.length} onClick={() => void act({ action: "confirm" })}>검증 후 확정</button><span>미배정 {unassigned.length}명</span></div>
      <section className="manage-panel" onDragOver={(event) => event.preventDefault()} onDrop={() => drop(null)}><h2>미배정</h2><div className="manage-toolbar">{unassigned.map((student) => <div draggable onDragStart={() => setDragId(student.id)} className="manage-person" key={student.id}><b>{student.name}</b><small>{student.grade || "?"}학년 · {student.service_part}부</small></div>)}</div></section>
      <div className="manage-group-board">{groups.data.groups.map((group) => { const members = groups.data.members.filter((item) => item.group_id === group.id); const leaders = groups.data.assignedStaff.filter((item) => item.group_id === group.id); return <section className="manage-group" key={group.id} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(group.id)}><h3>{group.name} <span className="manage-badge">{members.length}/{group.capacity}</span></h3><div className="manage-list">{members.map((member) => <div draggable onDragStart={() => setDragId(member.student_id)} className="manage-person" key={member.student_id}><span>{member.name}</span><small>이동 ↗</small></div>)}</div><label className="manage-field">담당 스탭<select className="manage-select" value={leaders[0]?.staff_id ?? ""} onChange={(event) => void act({ action: "assign_staff", groupId: group.id, staffId: event.target.value })}><option value="">미배정</option>{groups.data.staff.filter((staff) => staff.can_lead_group).map((staff) => <option key={staff.id} value={staff.id}>{staff.name}</option>)}</select></label></section>; })}</div>
    </div>}
  </main>;
}
