"use client";
import { useMemo, useState } from "react";
import { Notice, PageTitle, post, useApi } from "../_components/shared";

type Term = { id: string; name: string; status: string };
type Group = { id: string; name: string; capacity: number; required_staff: number; status: string };
type Student = { id: string; name: string; grade: number | null; gender: string | null; service_part: number; worship_team?: string | null };
type Staff = { id: string; name: string; can_lead_group: number };
type Member = { group_id: string; student_id: string; name: string; grade: number | null; gender: string | null; worship_team?: string | null };
type AssignedStaff = { group_id: string; staff_id: string; name: string };
type Rule = { id: string; type: string; config: { value?: string; minCount?: number }; student_ids: string[] };
type Settings = { studentMin: number; studentMax: number; staffMin: number; staffMax: number; clusterGender: boolean; clusterGrade: boolean; splitWorshipRole: boolean };
type GroupData = { groups: Group[]; members: Member[]; assignedStaff: AssignedStaff[]; rules: Rule[]; students: Student[]; staff: Staff[]; settings: Settings };
type ActionResult = { ok: boolean; warnings?: string[]; requiresConfirmation?: boolean };
const initialSettings: Settings = { studentMin: 1, studentMax: 8, staffMin: 1, staffMax: 1, clusterGender: false, clusterGrade: false, splitWorshipRole: false };
const ruleLabels: Record<string, string> = { together: "같은 조", apart: "다른 조", top_seed: "톱시드", gender_min: "성별 최소 인원", grade_min: "학년 최소 인원", role_min: "싱어·세션 최소 인원" };

export default function GroupsClient({ initialTermId = "" }: { initialTermId?: string }) {
  const terms = useApi<{ terms: Term[]; meetings: unknown[] }>("/api/terms", { terms: [], meetings: [] }); const [termId, setTermId] = useState(initialTermId); const activeId = termId || terms.data.terms.find((term) => term.status === "active")?.id || "";
  const groups = useApi<GroupData>(activeId ? `/api/groups?termId=${activeId}` : null, { groups: [], members: [], assignedStaff: [], rules: [], students: [], staff: [], settings: initialSettings }); const [message, setMessage] = useState(""); const [dragId, setDragId] = useState(""); const [ruleType, setRuleType] = useState("together"); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [ruleValue, setRuleValue] = useState("남"); const [ruleMin, setRuleMin] = useState(1);
  const assignedIds = new Set(groups.data.members.map((item) => item.student_id)); const unassigned = groups.data.students.filter((student) => !assignedIds.has(student.id)); const names = useMemo(() => new Map(groups.data.students.map((student) => [student.id, student.name])), [groups.data.students]);
  const act = async (body: Record<string, unknown>) => { try { let result = await post<ActionResult>("/api/groups", { ...body, termId: activeId }); if (result.requiresConfirmation) { const approved = window.confirm(`다음 조건을 확인해주세요.\n\n${result.warnings?.map((warning) => `• ${warning}`).join("\n")}\n\n그래도 진행할까요?`); if (!approved) { setMessage("이동을 취소했습니다."); return result; } result = await post<ActionResult>("/api/groups", { ...body, termId: activeId, force: true }); } setMessage(result.warnings?.join(" ") || "저장했습니다."); await groups.reload(); return result; } catch (error) { setMessage((error as Error).message); return { ok: false }; } };
  const configure = (form: FormData) => act({ action: "configure", count: form.get("count"), studentMin: form.get("studentMin"), studentMax: form.get("studentMax"), staffMin: form.get("staffMin"), staffMax: form.get("staffMax") });
  const saveModes = (change: Partial<Settings>) => act({ action: "save_modes", clusterGender: groups.data.settings.clusterGender, clusterGrade: groups.data.settings.clusterGrade, splitWorshipRole: groups.data.settings.splitWorshipRole, ...change });
  const addRule = async () => { const relationship = ["together", "apart", "top_seed"].includes(ruleType); const result = await act({ action: "add_rule", ruleType, studentIds: relationship ? selectedIds : [], value: relationship ? undefined : ruleValue, minCount: relationship ? undefined : ruleMin }); if (result.ok) setSelectedIds([]); };
  const drop = (groupId: string | null) => { if (dragId) void act({ action: "assign_student", studentId: dragId, groupId }); setDragId(""); };
  const setType = (value: string) => { setRuleType(value); setSelectedIds([]); setRuleValue(value === "grade_min" ? "1" : value === "role_min" ? "싱어" : "남"); };
  const selectedTerm = terms.data.terms.find((term) => term.id === activeId);

  return <main className="manage-content group-page">{initialTermId && <a className="term-back" href={`/manage/terms/${initialTermId}`}>← 학기 운영 메뉴</a>}<PageTitle eyebrow="02 · GROUP" title="조 편성" detail={`${selectedTerm?.name ?? "선택한 학기"}의 정원과 조건을 정하고 자동 편성한 뒤 수동으로 조정합니다.`} action={!initialTermId ? <select className="manage-select" value={activeId} onChange={(event) => setTermId(event.target.value)}><option value="">학기 선택</option>{terms.data.terms.map((term) => <option value={term.id} key={term.id}>{term.name}</option>)}</select> : undefined} />
    {!activeId ? <Notice>먼저 학기를 생성해주세요.</Notice> : <div className="manage-stack">
      <section className="manage-panel group-setup"><div className="group-section-copy"><p>STEP 1</p><h2>조와 정원 설정</h2><span>정원은 학생 기준입니다. 전체 인원이 나누어떨어지지 않아도 최소·최대 범위 안에서 배정합니다.</span></div><form className="group-capacity-form" key={`${groups.data.settings.studentMin}:${groups.data.settings.studentMax}:${groups.data.settings.staffMin}:${groups.data.settings.staffMax}`} action={(form) => void configure(form)}><label className="manage-field">조 수<input className="manage-input" name="count" type="number" min="1" defaultValue={groups.data.groups.length || 4} /></label><label className="manage-field">학생 최소<input className="manage-input" name="studentMin" type="number" min="1" defaultValue={groups.data.settings.studentMin} /></label><label className="manage-field">학생 최대<input className="manage-input" name="studentMax" type="number" min="1" defaultValue={groups.data.settings.studentMax} /></label><label className="manage-field">스탭 최소<input className="manage-input" name="staffMin" type="number" min="0" defaultValue={groups.data.settings.staffMin} /></label><label className="manage-field">스탭 최대<input className="manage-input" name="staffMax" type="number" min="0" defaultValue={groups.data.settings.staffMax} /></label><button className="manage-button primary">조 초안 만들기</button></form></section>

      <section className="manage-panel group-modes"><div className="group-section-copy"><p>STEP 2</p><h2>편성 방향</h2><span>켜면 해당 기준으로 조를 확실하게 분리합니다. 끄면 가능한 한 균형 있게 섞습니다.</span></div><div className="group-switches"><ModeSwitch label="동성조" detail="성별이 같은 학생끼리" active={groups.data.settings.clusterGender} onClick={() => void saveModes({ clusterGender: !groups.data.settings.clusterGender })} /><ModeSwitch label="동학년조" detail="학년이 같은 학생끼리" active={groups.data.settings.clusterGrade} onClick={() => void saveModes({ clusterGrade: !groups.data.settings.clusterGrade })} /><ModeSwitch label="싱어·세션 분리" detail="예배 역할을 나누어 편성" active={groups.data.settings.splitWorshipRole} onClick={() => void saveModes({ splitWorshipRole: !groups.data.settings.splitWorshipRole })} /></div></section>

      <section className="manage-panel group-rules"><div className="group-section-copy"><p>STEP 3</p><h2>세부 조건</h2><span>조건 종류를 고르면 필요한 입력 항목이 나타납니다. 같은 조건에 학생을 여러 명 선택할 수 있습니다.</span></div><div className="rule-builder"><label className="manage-field">조건 종류<select className="manage-select" value={ruleType} onChange={(event) => setType(event.target.value)}><option value="together">같은 조</option><option value="apart">다른 조</option><option value="top_seed">톱시드 지명</option><option value="gender_min">성별 최소 인원</option><option value="grade_min">학년 최소 인원</option><option value="role_min">싱어·세션 최소 인원</option></select></label>{["together", "apart", "top_seed"].includes(ruleType) ? <div className="rule-student-picker"><p>{ruleType === "top_seed" ? "서로 다른 조를 이끌 톱시드를 선택하세요." : "이 조건을 함께 적용할 학생을 모두 선택하세요."}</p><div>{groups.data.students.map((student) => <label className={selectedIds.includes(student.id) ? "selected" : ""} key={student.id}><input type="checkbox" aria-label={`${student.name} 선택`} checked={selectedIds.includes(student.id)} onChange={() => setSelectedIds((current) => current.includes(student.id) ? current.filter((id) => id !== student.id) : [...current, student.id])} /><span><b>{student.name}</b><small>{student.grade || "?"}학년 · {student.gender || "성별 미입력"} · {student.worship_team || "팀 미지정"}</small></span></label>)}</div><small>{selectedIds.length}명 선택</small></div> : <div className="rule-minimum"><label className="manage-field">적용 대상<select className="manage-select" value={ruleValue} onChange={(event) => setRuleValue(event.target.value)}>{ruleType === "gender_min" && <><option value="남">남학생</option><option value="여">여학생</option></>}{ruleType === "grade_min" && <><option value="1">1학년</option><option value="2">2학년</option><option value="3">3학년</option></>}{ruleType === "role_min" && <><option value="싱어">싱어</option><option value="세션">세션</option></>}</select></label><label className="manage-field">조별 최소 인원<input className="manage-input" type="number" min="1" value={ruleMin} onChange={(event) => setRuleMin(Number(event.target.value))} /></label></div>}<button className="manage-button primary" type="button" disabled={["together", "apart", "top_seed"].includes(ruleType) && selectedIds.length < 2} onClick={() => void addRule()}>조건 추가</button></div>
        <div className="rule-list"><h3>적용 중인 조건 <span>{groups.data.rules.length}</span></h3>{groups.data.rules.map((rule) => <article key={rule.id}><span className={`rule-kind ${rule.type}`}>{ruleLabels[rule.type] ?? rule.type}</span><div><b>{rule.student_ids.length ? rule.student_ids.map((id) => names.get(id) ?? "알 수 없음").join(" · ") : `${rule.config.value} · 조별 최소 ${rule.config.minCount}명`}</b><small>{rule.type === "top_seed" ? "선택한 학생들을 서로 다른 조에 배정" : rule.type === "together" ? "선택한 학생들을 모두 같은 조에 배정" : rule.type === "apart" ? "선택한 학생들을 모두 서로 다른 조에 배정" : "각 조가 충족해야 하는 최소 구성"}</small></div><button type="button" aria-label="조건 삭제" onClick={() => void act({ action: "delete_rule", ruleId: rule.id })}>삭제</button></article>)}{!groups.data.rules.length && <Notice>아직 추가한 조건이 없습니다.</Notice>}</div>
      </section>

      {message && <Notice error={message.includes("없") || message.includes("초과") || message.includes("부족") || message.includes("충돌")}>{message}</Notice>}
      <div className="group-actions"><div><b>STEP 4 · 편성 결과</b><span>미배정 {unassigned.length}명 · 학생 {groups.data.students.length}명</span></div><div><button className="manage-button primary" disabled={!groups.data.groups.length} onClick={() => void act({ action: "auto", seed: Date.now() % 100000 })}>새 자동 편성안</button><button className="manage-button" disabled={!groups.data.groups.length} onClick={() => void act({ action: "confirm" })}>검증 후 확정</button></div></div>
      <section className="manage-panel unassigned-zone" onDragOver={(event) => event.preventDefault()} onDrop={() => drop(null)}><h2>미배정 학생 <span>{unassigned.length}</span></h2><div className="group-person-pool">{unassigned.map((student) => <StudentCard student={student} key={student.id} onDrag={() => setDragId(student.id)} />)}</div></section>
      <div className="manage-group-board">{groups.data.groups.map((group) => { const members = groups.data.members.filter((item) => item.group_id === group.id); const leaders = groups.data.assignedStaff.filter((item) => item.group_id === group.id); const availableStaff = groups.data.staff.filter((staff) => !groups.data.assignedStaff.some((item) => item.staff_id === staff.id)); return <section className="manage-group group-column" key={group.id} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(group.id)}><header><div><h3>{group.name}</h3><small>학생 {groups.data.settings.studentMin}–{groups.data.settings.studentMax} · 스탭 {groups.data.settings.staffMin}–{groups.data.settings.staffMax}</small></div><span className={`manage-badge${members.length < groups.data.settings.studentMin || members.length > groups.data.settings.studentMax ? " warn" : ""}`}>{members.length}명</span></header><GroupSummary members={members} /><div className="manage-list">{members.map((member) => <StudentCard student={member} key={member.student_id} onDrag={() => setDragId(member.student_id)} />)}</div><div className="group-staff-box"><b>담당 스탭 <span>{leaders.length}명</span></b>{leaders.map((leader) => <div className="group-staff-chip" key={leader.staff_id}><span>{leader.name}</span><button type="button" aria-label={`${leader.name} 스탭 제외`} onClick={() => void act({ action: "remove_staff", staffId: leader.staff_id, groupId: group.id })}>×</button></div>)}{leaders.length < groups.data.settings.staffMax && <select className="manage-select" value="" onChange={(event) => { if (event.target.value) void act({ action: "assign_staff", groupId: group.id, staffId: event.target.value }); }}><option value="">스탭 추가</option>{availableStaff.map((staff) => <option key={staff.id} value={staff.id}>{staff.name}{staff.can_lead_group ? " · 조 담당 가능" : ""}</option>)}</select>}</div></section>; })}</div>
    </div>}
  </main>;
}

function ModeSwitch({ label, detail, active, onClick }: { label: string; detail: string; active: boolean; onClick: () => void }) { return <button type="button" className={active ? "active" : ""} aria-pressed={active} onClick={onClick}><span><b>{label}</b><small>{detail}</small></span><i><em /></i></button>; }
function StudentCard({ student, onDrag }: { student: Partial<Student> & { name: string; id?: string; student_id?: string }; onDrag: () => void }) { return <div draggable onDragStart={onDrag} className="manage-person group-student-card"><span><b>{student.name}</b><small>{student.grade || "?"}학년 · {student.gender || "성별 미입력"} · {student.worship_team === "싱어팀" ? "싱어" : "세션"}</small></span><small>이동 ↗</small></div>; }
function GroupSummary({ members }: { members: Member[] }) { const count = (value: string) => members.filter((member) => member.gender?.includes(value)).length; const grades = [1, 2, 3].map((grade) => `${grade}학년 ${members.filter((member) => member.grade === grade).length}`); const singers = members.filter((member) => member.worship_team === "싱어팀").length; return <div className="group-summary"><span>남 {count("남")} · 여 {count("여")}</span><span>{grades.join(" · ")}</span><span>싱어 {singers} · 세션 {members.length - singers}</span></div>; }
